version: 0.2

phases:
  pre_build:
    commands:
      - uname -a
      - pwd
      - ls
      - env | sort
      - ls /etc/*release*
      - cat /etc/*release*
      - whoami
      - gem install --no-document ufo
      # - configure ~/.aws/config default
  build:
    commands:
      - echo Build started on `date`
      - echo Building project...
      - uptime
      - ufo docker build
      - ufo tasks build
      - grep region .ufo/output/demo-web.json

      # - ufo current --service demo-web
      # - ufo ship
      # - .codebuild/acceptance.sh
cache:
  paths:
    - /usr/local/bundle
    - /usr/local/lib/ruby/gems/2.5.0
# artifacts:
#   files:
#     - result.txt
